export const imageGallery = {
    "message": "get image gallery informations",
    "data": [
        {
            "src": "../assets/images/gallery/1.jpg",
            "name": "Nathan Guerrero",
            "timeStamp": "12 hrous ago",
            "view": 112,
            "like": 42,
            "team": "Development Team",
        },
        {
            "src": "../assets/images/gallery/2.jpg",
            "name": "Alice Mason",
            "timeStamp": "1 hrous ago",
            "view": 112,
            "like": 42,
            "team": "DevOps Team",
        },
        {
            "src": "../assets/images/gallery/3.jpg",
            "name": "Rose Bradley",
            "timeStamp": "5 hrous ago",
            "view": 112,
            "like": 42,
            "team": "Testing Team",
        },
        {
            "src": "../assets/images/gallery/4.jpg",
            "name": "Peter Richards",
            "timeStamp": "6 hrous ago",
            "view": 112,
            "like": 42,
            "team": "Testing Team",
        },
        {
            "src": "../assets/images/gallery/5.jpg",
            "name": "Wayne Holland",
            "timeStamp": "8 hrous ago",
            "view": 112,
            "like": 42,
            "team": "DevOps Team",
        },
        {
            "src": "../assets/images/gallery/6.jpg",
            "name": "Michelle Ross",
            "timeStamp": "4 hrous ago",
            "view": 112,
            "like": 42,
            "team": "Development Team",
        },
        {
            "src": "../assets/images/gallery/7.jpg",
            "name": "Debra Beck",
            "timeStamp": "12 hrous ago",
            "view": 112,
            "like": 42,
            "team": "Development Team",
        },
        {
            "src": "../assets/images/gallery/8.jpg",
            "name": "Phillip Peters",
            "timeStamp": "6 hrous ago",
            "view": 112,
            "like": 42,
            "team": "DevOps Team",
        },
        {
            "src": "../assets/images/gallery/9.jpg",
            "name": "Jack Ruiz",
            "timeStamp": "10 hrous ago",
            "view": 112,
            "like": 42,
            "team": "Testing Team",
        },
        {
            "src": "../assets/images/gallery/10.jpg",
            "name": "Ronald Bradley",
            "timeStamp": "7 hrous ago",
            "view": 112,
            "like": 42,
            "team": "Testing Team",
        },
        {
            "src": "../assets/images/gallery/11.jpg",
            "name": "Kathleen Harper",
            "timeStamp": "8 hrous ago",
            "view": 112,
            "like": 42,
            "team": "DevOps Team",
        },
        {
            "src": "../assets/images/gallery/12.jpg",
            "name": "Bobby Knight",
            "timeStamp": "2 hrous ago",
            "view": 112,
            "like": 42,
            "team": "DevOps Team",
        }
    ]
}